DROP DATABASE IF EXISTS DEV_GW_CDA;

-- Initial setup of roles, Database, Schemas and necessary privileges
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS DEV_GW_CDA;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEV_GW_CDA_OWNER;
GRANT ROLE DEV_GW_CDA_OWNER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

GRANT OWNERSHIP ON DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_OWNER;

-- In case of future grants, apart from accountadmin/securityadmin role no other role can perform 
-- grant or revoke privileges even though the role is the owner of the database or schema object. 

USE ROLE SECURITYADMIN;

GRANT MANAGE GRANTS ON ACCOUNT TO ROLE DEV_GW_CDA_OWNER;

USE ROLE DEV_GW_CDA_OWNER;

GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_OWNER;

USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS DEV_GW_CDA.CDA_PC_RAW 
  WITH MANAGED ACCESS 
  COMMENT = 'schema for cda pc raw data objects';

CREATE SCHEMA IF NOT EXISTS DEV_GW_CDA.CDA_PC_MERGED 
  WITH MANAGED ACCESS 
  COMMENT = 'schema for cda pc merged data objects';

CREATE SCHEMA IF NOT EXISTS DEV_GW_CDA.CDA_ABC_SHARED 
  WITH MANAGED ACCESS 
  COMMENT = 'schema for cda shared data objects';

SHOW SCHEMAS IN DATABASE DEV_GW_CDA;

--------------------------------------------------------
-- Schema specific commands for CDA_PC_RAW
--------------------------------------------------------

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_PC_RAW_READ;
CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_PC_RAW_WRITE;

-- GRANT READ ROLE TO WRITE ROLE
GRANT ROLE DEV_GW_CDA_CDA_PC_RAW_READ TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;

-- GRANTS TO READ ROLE
USE ROLE SYSADMIN;

GRANT USAGE, MONITOR ON DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE, MONITOR ON FUTURE SCHEMAS IN DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT ALL ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE, READ ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT MONITOR ON ALL TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

-- OBJECT GRANTS TO WRITE ROLE
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW 
  TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW 
  TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;

GRANT WRITE ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;

-- SET OBJECT FUTURE OWNERSHIP GRANTS TO OWNER ROLE
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;

--------------------------------------------------------
-- (Duplicated) GRANTS TO READ ROLE - CDA_PC_RAW (kept as-is)
--------------------------------------------------------

USE ROLE SYSADMIN;

GRANT USAGE, MONITOR ON DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE, MONITOR ON FUTURE SCHEMAS IN DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT ALL ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT USAGE, READ ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT SELECT ON ALL STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

GRANT MONITOR ON ALL TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ;

-- OBJECT GRANTS TO WRITE ROLE (duplicated block kept)
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW 
  TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW 
  TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;

GRANT WRITE ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE;

-- SET OBJECT FUTURE OWNERSHIP GRANTS TO OWNER ROLE (commented out duplicates kept)
-- GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;
-- GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_RAW TO ROLE DEV_GW_CDA_OWNER;

--------------------------------------------------------
-- Grants to CDA_PC_MERGED schema
--------------------------------------------------------

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_PC_MERGED_READ;
CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_PC_MERGED_WRITE;

-- GRANT READ ROLE TO WRITE ROLE
GRANT ROLE DEV_GW_CDA_CDA_PC_MERGED_READ TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE;

-- GRANTS TO READ ROLE
USE ROLE SYSADMIN;

GRANT USAGE, MONITOR ON DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE, MONITOR ON FUTURE SCHEMAS IN DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT SELECT ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT ALL ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT USAGE, READ ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT SELECT ON ALL STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

GRANT MONITOR ON ALL TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ;

-- OBJECT GRANTS TO WRITE ROLE
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED 
  TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED 
  TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE;

GRANT WRITE ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE;

-- SET OBJECT FUTURE OWNERSHIP GRANTS TO OWNER ROLE
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_PC_MERGED TO ROLE DEV_GW_CDA_OWNER;

--------------------------------------------------------
-- Grants to CDA_ABC_SHARED schema
--------------------------------------------------------

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_ABC_SHARED_READ;
CREATE ROLE IF NOT EXISTS DEV_GW_CDA_CDA_ABC_SHARED_WRITE;

-- GRANT READ ROLE TO WRITE ROLE
GRANT ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE;

-- GRANTS TO READ ROLE
USE ROLE SYSADMIN;

GRANT USAGE, MONITOR ON DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE, MONITOR ON FUTURE SCHEMAS IN DATABASE DEV_GW_CDA TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT SELECT ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT USAGE ON ALL FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT ALL ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT USAGE, READ ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT SELECT ON ALL STREAMS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

GRANT MONITOR ON ALL TASKS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ;

-- OBJECT GRANTS TO WRITE ROLE
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED 
  TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE;
GRANT DELETE, INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED 
  TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE;

GRANT WRITE ON ALL STAGES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE;

-- SET OBJECT FUTURE OWNERSHIP GRANTS TO OWNER ROLE
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;
GRANT OWNERSHIP ON FUTURE PIPES IN SCHEMA DEV_GW_CDA.CDA_ABC_SHARED TO ROLE DEV_GW_CDA_OWNER;

--------------------------------------------------------
-- Granting necessary privileges to roles to execute tasks
--------------------------------------------------------

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TASKADMIN;

-- Set the active role to ACCOUNTADMIN before granting the account-level privileges to the new role
USE ROLE ACCOUNTADMIN;

GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TASKADMIN;

-- Set the active role to SECURITYADMIN to show that this role can grant a role to another role
USE ROLE SECURITYADMIN;

GRANT ROLE TASKADMIN TO ROLE DEV_GW_CDA_OWNER;

--------------------------------------------------------
-- OBJECTS CREATION
--------------------------------------------------------

-- Storage Object creation and they should be created by user who has ACCOUNTADMIN role
USE ROLE ACCOUNTADMIN;
USE DATABASE DEV_GW_CDA;
USE SCHEMA CDA_ABC_SHARED;

CREATE STORAGE INTEGRATION IF NOT EXISTS DEV_S3_CDA_SF  
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::448734340866:role/role_for_snf'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://s3-to-snf-cda-bucket/');

GRANT OWNERSHIP ON INTEGRATION DEV_S3_CDA_SF TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

GRANT USAGE ON INTEGRATION DEV_S3_CDA_SF TO ROLE DEV_GW_CDA_OWNER;

DESC INTEGRATION DEV_S3_CDA_SF;
SHOW GRANTS ON INTEGRATION DEV_S3_CDA_SF;

-- File formats
USE ROLE DEV_GW_CDA_OWNER;
USE DATABASE DEV_GW_CDA;
USE SCHEMA CDA_ABC_SHARED;

CREATE OR REPLACE FILE FORMAT FF_CDA_PARQUET 
  TYPE = 'PARQUET' 
  COMPRESSION = 'AUTO' 
  BINARY_AS_TEXT = FALSE;

CREATE OR REPLACE FILE FORMAT FF_CDA_JSON 
  TYPE = 'JSON';

DESC FILE FORMAT FF_CDA_PARQUET;
DESC FILE FORMAT FF_CDA_JSON;

-- Creating log and audit tables
USE SCHEMA CDA_ABC_SHARED;

CREATE TABLE IF NOT EXISTS PC_CDA_LOGGING (
  LOG_INFO VARIANT, 
  EVENT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA CDA_ABC_SHARED;

CREATE TABLE IF NOT EXISTS PC_CDA_AUDIT_METRIC_RAW_ABC (
  CDA_RAW_TABLE_NAME VARCHAR,
  SRC_ROW_COUNT INTEGER,
  TGT_RAW_COUNT INTEGER,
  PARQUET_WRITE_TIMESTAMP TIMESTAMP_NTZ,
  SCHEMAHISTORY VARIANT,
  TARGET_LOAD_TIMESTAMP TIMESTAMP_NTZ,
  AUDIT_DIFF INTEGER,
  AUDIT_DIFF_PERCENT NUMBER (8,4)
);

-- CDA warehouse creation
SHOW WAREHOUSES;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS CDA_WH_XS
    WAREHOUSE_TYPE = STANDARD
    WAREHOUSE_SIZE = XSMALL
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    ENABLE_QUERY_ACCELERATION = FALSE
    QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8;

GRANT OPERATE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_OWNER WITH GRANT OPTION;
GRANT USAGE   ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_OWNER WITH GRANT OPTION;
-- GRANT MODIFY ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_OWNER WITH GRANT OPTION; -- NOT RECOMMENDED TO GRANT MODIFY PRIVILEGES TO DEV ROLES

GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_PC_RAW_READ       WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_PC_RAW_WRITE      WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_PC_MERGED_READ    WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_PC_MERGED_WRITE   WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_READ   WITH GRANT OPTION;
GRANT USAGE ON WAREHOUSE CDA_WH_XS TO ROLE DEV_GW_CDA_CDA_ABC_SHARED_WRITE  WITH GRANT OPTION;
